apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.product }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.product }}
      deploymentconfig: '{{ .Values.product }}'
  strategy:
    type: RollingUpdate
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.product }}
        deploymentconfig: '{{ .Values.product }}'
    spec:
      containers:
      - name: {{ .Values.product }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        resources:
          requests:
              cpu: '{{ .Values.cpuMin }}'
              memory: '{{ .Values.memoryMin }}'
            limits:
              cpu: '{{ .Values.cpuMax }}'
              memory: '{{ .Values.memoryMax }}'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
